# This can be run like this:
#   docker compose -f compose.dev.yml up --build

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: fastapi
        ports:
            - "8000:8000" # uvicorn
            - "5678:5678" # debugpy
        expose:
            - "8000"
        environment:
            - PYTHONDONTWRITEBYTECODE=1
            - PYTHONUNBUFFERED=1
            - PIP_NO_CACHE_DIR=1
        env_file: .env
        volumes:
            - .:/app
        command: [
            "python", "-m", "debugpy",
            "--listen", "0.0.0.0:5678",
            "-m", "uvicorn", "main:app",
            "--host", "0.0.0.0", "--port", "8000", "--reload"
        ]
        depends_on: [db, redis]
    worker:
      build:
        context: .
        dockerfile: Dockerfile
      container_name: fastapi-worker
      environment:
          - PYTHONDONTWRITEBYTECODE=1
          - PYTHONUNBUFFERED=1
          - PIP_NO_CACHE_DIR=1
      env_file: .env
      volumes:
        - .:/app
      command: ["rq", "worker", "-u", "${REDIS_URL:-redis://redis:6379/0}", "etl"]
      depends_on: [db, redis]
    db:
      image: postgres:16
      env_file: .env
      ports: ["5432:5432"]
      volumes:
        - ./data/postgres:/var/lib/postgresql/data
    migrate:
      build: .
      env_file: .env
      depends_on: [db]
      command: ["alembic", "upgrade", "head"]
    ngrok:
        image: ngrok/ngrok:latest
        container_name: ngrok
        depends_on:
        - app
        env_file: .env
        command:
        - "http"
        - "--domain=${DOMAIN}"
        - "app:8000"
        ports:
        - "4040:4040" 
    redis:
        image: "redis:alpine"
        container_name: redis
        ports:
          - "6379:6379"
        volumes:
          - ./data/redis:/data
    minio:
        image: minio/minio:latest
        command: ["server", "/data", "--console-address", ":9001"]
        environment:
            MINIO_ROOT_USER: devminio
            MINIO_ROOT_PASSWORD: devminio12345
        ports:
          - "9000:9000"
          - "9001:9001"
        volumes:
          - ./minio-data:/data
        healthcheck:
            test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
            interval: 10s
            timeout: 5s
            retries: 5

    minio-setup:
        image: minio/mc:latest
        depends_on:
            minio:
                condition: service_healthy
        entrypoint: >
          /bin/sh -c "
          mc alias set local http://minio:9000 devminio devminio12345 &&
          mc mb -p local/analytics || true &&
          mc version enable local/analytics || true
          "
volumes:
  pgdata: {}